<?php

namespace AppBundle\Repository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends \Doctrine\ORM\EntityRepository
{


    public function Affichage($id)
    {
        /*$em = $this->getDoctrine()->getManager();
        $RAW_QUERY = 'select r.idRealisation as id, f.nom as filmnom,a.nom as acteurnom ,f.id as idfilm from film fdJOIN realisation r on r.idfilm=f.id join acteur a on r.idacteur=a.id';
        $statement = $em->getConnection()->prepare($RAW_QUERY);
        $statement->execute();
        return $statement->fetchAll();*/
        $query = $this->getEntityManager()
            ->createQuery("SELECT s.id as idsponsor,s.nom as noms, s.adresse as adresse,s.telephone as telephone,s.email as emails,s.logo as logos ,a.sponsor as idsponsoragence, a.nom as nom ,a.matriculeFiscale as matricule ,a.adresse as addr ,a.telephone as tel ,a.fax as fax,a.site as site ,a.email as email,a.logo as logo from AppBundle:Agence a JOIN AppBundle:Sponsor s WITH a.idsponsoragence = s.idsponsor   WHERE a.id =:id")
        ->setParameter('id', $id);
        return $query->getResult();

    }

    public function  agenceByUtilisateur($user)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a 
                FROM AppBundle:Agence a 
                WHERE a.utilisateurProfessionnel =:id '
            )
            ->setParameter('id', $user)
            ->getResult();

    }
}
