<?php

namespace AppBundle\Repository;

/**
 * CommentairePublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairePublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
