<?php

namespace AppBundle\Repository;

/**
 * PublicationLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
