<?php

namespace AppBundle\Repository;

/**
 * SponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorRepository extends \Doctrine\ORM\EntityRepository
{


    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s
                FROM AppBundle:Sponsor s
                WHERE s.nom LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

}
