imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@GestionPublicationBundle/Resources/config/services.yml" }
    - { resource: "@GestionEvenementBundle/Resources/config/services.yml" }
    - { resource: "@GestionAgenceBundle/Resources/config/services.yml" }
    - { resource: "@ArticleBundle/Resources/config/services.yml" }


# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    templating:
        engines: ['twig']
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "slimkarboul@gmail.com"
        sender_name: "slimkarboul"
    registration:
        form:
            type: AppBundle\Form\UserType
gregwar_captcha: ~
vresh_twilio:
    #(Required) Your Account SID from www.twilio.com/user/account
    sid: 'AC5d4e3daefd8967e3601bb87b7ecb3f3b'
    #(Required) Your Auth Token from www.twilio.com/user/account
    authToken: '4a2197b2c7055658c64011a4c8034e41'

# Windows configuration
knp_snappy:
    pdf:
        enabled:    true
        # If you have wkhtmltopdf as an environment variable you don't need to provide the
        # full path to the executable, use it in the same way as you use in the console
        #binary:  "wkhtmltopdf"
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:
            no-outline: true
            page-size: LETTER
            # Recommended to set UTF-8 as default encoding :)
            encoding: UTF-8
    image:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []


nomaya_social:
    buttons:
        facebook:
            url:    "www.faceboo.com/Esprit"
            locale: "fr_FR"
            send:   false
            width:  300
            showFaces:  false
            layout: "button_count"
        twitter:
            url:    null
            locale: "fr"
            message: "Je veux partager ça avec vous"
            text:   "Tweet"
            via:    "Esprit Sponsor"
            tag:    "Esprit"
        googleplus:
            url:    null
            locale: "fr"
            size: "medium"
            annotation: "bubble"
            width:  300
        linkedin:
            url:    null
            locale: "fr_FR"
            counter:    "right"
        pinterest:
            url:    null
    theme:          'default' # optional
vich_uploader:
    db_driver: orm
    mappings:
        taswira:
            uri_prefix:         /uploads/article/photo
            upload_destination: %kernel.root_dir%/../web/uploads/article/photo
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true


