article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

gestion_agence:
    resource: "@GestionAgenceBundle/Resources/config/routing.yml"
    prefix:   /

gestion_evenement:
    resource: "@GestionEvenementBundle/Resources/config/routing.yml"
    prefix:   /

gestion_publication:
    resource: "@GestionPublicationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

