<?php

namespace ArticleBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLikes()
    {

        $query = $this->getEntityManager()
            ->createQuery("select count(r.idrate) as cnt from BlogBundle:Rating r WHERE r.type='Like'");
        return $query->getResult();

    }

    public function getRating($iduser,$idarticle)
    {

        $query = $this->createQueryBuilder('r')
            ->where('r.user = :iduser')
            ->andWhere('r.article = :idarticle')
            ->setParameters(array(
                    'iduser'=>$iduser,
                    'idarticle'=>$idarticle,
                )
            )
            ->getQuery();
        return $query->getResult();
    }
}
